### ISSUE TITLE
Make Tokenize thread safe

### ISSUE THREAD

**Issue by ZacLN** [JuliaLang/Tokenize.jl#102]
Let's strip `charstore`, collect read `Char`s on the fly and only for tokens that need it (i.e. not keywords, operators etc.), and only allow accessing `sometoken.val` through `value(sometoken)`

**Comment by KristofferC** [comment]
Alternatively, we could just make a new `charstore` for each `Lexer` (save it in the struct).

**Comment by KristofferC** [comment]
Another thing I was thinking about was to just not store any strings, and instead, extract them from the original buffer  @object. That might be awkward though.

**Comment by ZacLN** [comment]
I think the major slowdown is `extract_tokenstring` reversing through the buffer, so to avoid that would be great. For `\base` non-inferrable tokens (i.e. can't work out their `.val` from their `kind`) make up just under half of all tokens, for some of these collecting their value as we track them is easy (i.e. comments, whitespace) for other's it'll need a bit more finess.

I tried a no-val-token before  with an earlier instance of CSTParser and it was really really slow to pop around querying random portions of the text

**Comment by KristofferC** [comment]
I benchmarked before and it seems that Tokenizing the input is ~10% of the time it takes to parse a file with CSTParser. So speed ups here would only lead to marginal speedups of the parsing?

**Comment by ZacLN** [comment]
I did a bit of testing and it seemed to become more of a problem when you parsed loads of files sequentially, I think w/ the profiler rather than explicit timings

**Comment by KristofferC** [comment]
Ok, I think your strategy in the first post should work.

**Comment by ZacLN** [comment]
Also, do you use `startpos`/`endpos` ?

**Comment by KristofferC** [comment]
Nope, but they should be pretty much free to store?

**Comment by ZacLN** [comment]
Yep not costly, just curious

**Comment by KristofferC** [comment]
I think https://github.com/KristofferC/Tokenize.jl/blob/master/src/utilities.jl#L143 still needs to be dealt with. Could perhaps use a function local `Ref` that should be optimized away on 0.7.

**Comment by KristofferC** [comment]
Should be no global state now.
