### ISSUE TITLE
Store operator metainfo here

### ISSUE THREAD

**Issue by ZacLN** [JuliaLang/Tokenize.jl#119]
@KristofferC, thoughts on me moving a whole bunch of helper functions from CSTParser that operate on `Kind` and `Token` to Tokenize?

Edit: there are some that I think definately belong here (i.e. `isidentifier`) and some I'm less sure of such as `is_non_dotted_op`

**Comment by KristofferC** [comment]
As long as they have a use without CSTParser, it should be fine to move them here.
