### ISSUE TITLE
`:keyword` incorrectly tokenized

### ISSUE THREAD

**Issue by pfitzseb** [JuliaLang/Tokenize.jl#120]
E.g.:
```
julia> collect(Tokenize.tokenize(":module"))
3-element Array{Tokenize.Tokens.Token,1}:
 1,1-1,1          OP             ":"     
 1,2-1,7          KEYWORD        "module"
 1,8-1,7          ENDMARKER      ""      
```

**Comment by ZacLN** [comment]
I don't think there's an alternative to this

**Comment by pfitzseb** [comment]
Why? I can kinda see that it's not generally possible to correctly tokenize that as `1,1-1,7  SYMBOL  ":module"`, but
```
 1,1-1,1          OP             ":"     
 1,2-1,7         IDENTIFIER        "module"
```
certainly seems possible?

**Comment by ZacLN** [comment]
But it _is_ a keyword, it's only when parsing that we consider this singular special case (i.e. consider the context of a token). The alternative is to treat all keywords as identifiers and add a series of special cases

**Comment by KristofferC** [comment]
Also, in stuff like `true?1:function`, `1:function` etc, it seems like it could be difficul to realize that `:function` is not a symbol.

**Comment by ZacLN** [comment]
Yeah, this why there's a hard(ish) line between lexer and parser.
EDIT: by which I mean- I don't think returning the `kind` of a token is strictly the lexers job

**Comment by pfitzseb** [comment]
Fair enough -- ~~I guess it could be possible for *most* keywords, but `function` is indeed a notable exception~~ :)
