### ISSUE TITLE
startbyte(t::Token) and endbyte(t::Token) are documented but do not exist

### ISSUE THREAD

**Issue by yurivish** [JuliaLang/Tokenize.jl#121]
The documentation in the README (https://github.com/KristofferC/Tokenize.jl#tokens) states that the API for a token includes the following two functions:

```julia
startbyte(T)::Int            # byte offset where the token start
endbyte(t)::Int              # byte offset where the token ends
```

Looking at the code, it doesn't look like these actually exist — should they? It looks like the canonical way to access these right now is by direct access to the field on the token.

https://github.com/KristofferC/Tokenize.jl/search?utf8=%E2%9C%93&q=startbyte

**Comment by KristofferC** [comment]
Hm, these should exist. Perhaps they got lost...

**Comment by KristofferC** [comment]
Ah I think they are called `startpos` etc.

**Comment by yurivish** [comment]
It looks like that's different:

```julia
julia> x = first(collect(tokenize("function foo end")))
1,1-1,8          KEYWORD        "function"
julia> x.startpos
(1, 1)
julia> Tokenize.Tokens.startpos(x)
(1, 1)
julia> x.startbyte
0
julia> Tokenize.Tokens.startbyte(x)
ERROR: UndefVarError: startbyte not defined
```

The docs in the readme (https://github.com/KristofferC/Tokenize.jl#tokens) mention startpos, so it's good that it exists, but it doesn't do the same thing as startbyte:

```julia
startpos(t)::Tuple{Int, Int} # row and column where the token start
endpos(t)::Tuple{Int, Int}   # row and column where the token ends
startbyte(T)::Int            # byte offset where the token start
endbyte(t)::Int              # byte offset where the token ends
```

**Comment by KristofferC** [comment]
Yeah, I was confused. Those are indeed different.

**Comment by KristofferC** [comment]
Done
