### ISSUE TITLE
Dot operators have inconsistent location information

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/Tokenize.jl#139]
First time playing with Tokenize.jl so this might be me misunderstanding something.

```
julia> collect(Tokenize.tokenize("//\n./"))
4-element Array{Tokenize.Tokens.Token,1}:
 1,1-1,2          OP             "//"
 1,3-2,0          WHITESPACE     "\n"
 2,0-2,2          OP             "./"
 2,3-2,2          ENDMARKER      "" 
```

I did not expect the `./` going from `2,0-2,2`. Same with `startbyte`/`endbyte`, returning `0:1` for the `//` but `2:4` for the `./`. Worse if starting the file with a dot operator:

```
julia> collect(Tokenize.tokenize("./"))
2-element Array{Tokenize.Tokens.Token,1}:
 1,0-1,2          OP             "./"
 1,3-1,2          ENDMARKER      ""  

julia> Tokens.startbyte(collect(Tokenize.tokenize("./"))[1])
-1
```

**Comment by KristofferC** [comment]
Seems like https://github.com/KristofferC/Tokenize.jl/blob/950b224f4ce7e962f08264ae73be8a03bb6a7e12/src/lexer.jl#L259-L264 has a -1 added to the `startpos` if it is a dot operator. Introduced in https://github.com/KristofferC/Tokenize.jl/pull/129. Not sure what reason, @ZacLN?
