### ISSUE TITLE
incorrect RBITSHIFT lexing?

### ISSUE THREAD

**Issue by ZacLN** [JuliaLang/Tokenize.jl#17]
```
using Tokenize
collect(Tokenize.tokenize(">> "))[1]
```
gives `OP ">> "` rather than `RBITSHIFT` and a single `WHITESPACE`.

I can [see](https://github.com/KristofferC/Tokenize.jl/blob/master/src/lexer.jl#L391) that this is done intentionally but can't tell why?

**Comment by KristofferC** [comment]
Feels like a bug.

**Comment by ZacLN** [comment]
Ok, I'll add a PR with test
