### ISSUE TITLE
incorrect attribute values for tokens of the KEYWORD category

### ISSUE THREAD

**Issue by alexfdo** [JuliaLang/Tokenize.jl#174]
A)
julia> using Tokenize

julia> d = collect(tokenize("using DataFrames"))
4-element Array{Tokenize.Tokens.Token,1}:
 1,1-1,5          KEYWORD        "using"
 1,6-1,6          WHITESPACE     " "
 1,7-1,16         IDENTIFIER     "DataFrames"
 1,17-1,16        ENDMARKER      ""

julia> d[3].val
"DataFrames"

julia> d[1].val
""
julia> d[1].kind
USING::Kind = 42

B)
julia> d = collect(tokenize("function filter_df_1(df)"))
7-element Array{Tokenize.Tokens.Token,1}:
 1,1-1,8          KEYWORD        "function"
 1,9-1,9          WHITESPACE     " "
 1,10-1,20        IDENTIFIER     "filter_df_1"
 1,21-1,21        LPAREN         "("
 1,22-1,23        IDENTIFIER     "df"
 1,24-1,24        RPAREN         ")"
 1,25-1,24        ENDMARKER      ""

julia> d[1].val
""

julia> d[1].kind
FUNCTION::Kind = 24

**Comment by ZacLN** [comment]
I think you may be looking for `untokenize`

**Comment by alexfdo** [comment]
Thanks a lot for the advice. I looked at untokenize, but it is the tokenize that I need. 
And also I need the attributes of the first token to display the correct values as well, as in all other tokens.
  
>Вторник, 23 марта 2021, 0:46 +03:00 от ZacNugent ***@***.***>:
> 
> 
>I think you may be looking for untokenize
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
alex grig

**Comment by alexfdo** [comment]
> I think you may be looking for `untokenize`

Thanks a lot for the advice. I looked at untokenize, but it is the tokenize that I need. 
And also I need the attribute values of the tokens of the KEYWORD category to have the correct values, like the tokens of other categories.

**Comment by pfitzseb** [comment]
There's no point in storing the `val` of a keyword token since it can be generated from its kind. So as Zac said above, use `untokenize` if you want to go back from a token to its textual representation.

**Comment by alexfdo** [comment]
ОК! 
"untokenize" is fine for token values, but what about a kind? What reverse operation can I use to get the correct attribute value = KEYWORD (not  "FUNCTION", not "USING" ... namely  "KEYWORD")?

**Comment by pfitzseb** [comment]
`Tokens.kind(t)` gives you the "abstract kind" (so e.g. `KEYWORD`), as opposed to `Tokens.exactkind(t)`. I don't think you should ever need to access fields directly.

**Comment by alexfdo** [comment]
> I don't think you should ever need to access fields directly.

Maybe 90% of your statement is true, but not in my case. I use the results of parsing Julia's code to then process it in python.
Thank you very much for your help, you helped me a lot. I think the topic can be closed.
Sincerely, Alexander

**Comment by pfitzseb** [comment]
What I meant by that is that if you end up having to access fields directly then we should maybe add a function for that here.

**Comment by alexfdo** [comment]
It would be nice if the parser could output in parallel in json format what it prints))
