### ISSUE TITLE
Can you tokenize a string with a regular expression

### ISSUE THREAD

**Issue by Nick-Mul** [JuliaLang/Tokenize.jl#204]
Sorry new to Julia and trying to tokenize a smiles string, and was wondering if it would be possible to use this package?

The python code is: 
```
import re
SMI_REGEX_PATTERN = "(\[[^\]]+]|Br?|Cl?|N|O|S|P|F|I|b|c|n|o|s|p|\(|\)|\.|=|#||\+|\\\\\/|:||@|\?|>|\*|\$|\%[0–9]{2}|[0–9])"
smiles = "CC(=O)OC1=CC=CC=C1C(=O)O"
tokens = [token for token in re.findall(SMI_REGEX_PATTERN, smiles)]
print(tokens)
```
['C', 'C', '(', '=', 'O', ')', 'O', 'C', '', '=', 'C', 'C', '=', 'C', 'C', '=', 'C', '', 'C', '(', '=', 'O', ')', 'O', '']

I was wondering how to do this in Julia? The direct translation doesn't quite work.
```
SMI_REGEX_PATTERN = r"(\[[^\]]+]|Br?|Cl?|N|O|S|P|F|I|b|c|n|o|s|p|\(|\)|\.|=|#||\+|\\\\\/|:||@|\?|>|\*|\$|\%[0–9]{2}|[0–9])"
smiles = "CC(=O)OC1=CC=CC=C1C(=O)O"
m =[token for token in findall(SMI_REGEX_PATTERN, smiles)]
```

**Comment by KristofferC** [comment]
Hello, this package is for tokenizing Julia source code. You might be interested in something more like https://github.com/BioJulia/Automa.jl.

**Comment by pfitzseb** [comment]
Also, your code works fine if you use `eachmatch` instead of `findall`:
```
julia> [m.match for m in eachmatch(SMI_REGEX_PATTERN, smiles)]
25-element Vector{SubString{String}}:
 "C"
 "C"
 "("
...
```

**Comment by Nick-Mul** [comment]
Awesome thanks guys :) Have a good day!!
