### ISSUE TITLE
lexer code's use of string

### ISSUE THREAD

**Issue by spaette** [JuliaLang/Tokenize.jl#212]
@ZacLN

What's the basis for use of the string `somtext`?

**fix lexer, add tests**
committed on Jan 26, 2017

test/lexer.jl

I note the string has also been used in the JuliaSyntax package.

**Comment by KristofferC** [comment]
It's just some text.

**Comment by spaette** [comment]
didn't know if `sometext` might have been the author's intention

anyways there is a pull for fixing typos over in the JuliaSyntax repo

**Comment by KristofferC** [comment]
It doesn't matter, it could be "ifdjhsflkds"
