### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Tokenize.jl#31]
I tokenized all local packages looking for error tokens and found the following:

### Dot power (fixed by #29)
```julia
collect(tokenize("2.0.^[0.5,0,1])"))[1]

1,1-1,4:   ERROR	"2.0."
```

### Double transposing (fixed by #34)
```julia
collect(tokenize(
"""
ImageMagick.save(fn, reinterpret(ARGB32, [0xf0884422]''))
D = ImageMagick.load(fn)
"""))[end-1]

1,55-3,0:   ERROR   "'))\nD = ImageMagick.load(fn)\n"
```

### Empty comment followed by triple string (fixed by #32)
```julia
collect(tokenize("""
#
\"\"\"
f
\"\"\"
1
"""))[end-1]

4,1-6,0:   ERROR	"\"\"\"\n1\n"
```

**Comment by KristofferC** [comment]
The transpose part seems hard because it seems that you have to be more context aware to figure it out. Looking one token back is not enough I think :(

**Comment by ZacLN** [comment]
Am I missing something or does 
```
    elseif l.last_token == Tokens.PRIME
        return emit(l, Tokens.PRIME)
```

below [this](https://github.com/KristofferC/Tokenize.jl/blob/6c019034ac48c03f4bb78ed553ada950b0eb8bfc/src/lexer.jl#L627) do the trick?

**Comment by ZacLN** [comment]
... and have `lex_prime` emit `''` as two 'PRIME's rather than an (invalid in terms of the parser) empty `Char`.

**Comment by KristofferC** [comment]
Yeah that might work :)

**Comment by ZacLN** [comment]
I've done a PR, also changed the `in` to explicit OR statements as it's a small list

**Comment by ZacLN** [comment]
This is all fixed now, right?

**Comment by KristofferC** [comment]
Yep! What fixed the `2.0.^` case?

**Comment by ZacLN** [comment]
#29 ?

**Comment by KristofferC** [comment]
Oh yeah, of course. Thanks!
