### ISSUE TITLE
Investigate performance of stringless tokens

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Tokenize.jl#39]
Instead the lexer holds a reference to the string, buffer whatever, and that is used as a lookup for the tokens. So you would have `untokenize(token, lexer)`. Means, tokens can be allocated on the stack. Would be interesting to see if there is a significant performance difference.

**Comment by ZacLN** [comment]
I was pondering this very thing this afternoon. 

Just running through tokens: 
```
str = readstring(Base.find_source_file("inference.jl"))

function cyclethrough(str)
    l = tokenize(str)
    while !Tokenize.Lexers.eof(l)
        Tokenize.Lexers.next_token(l)
    end 
end
@time cyclethrough(str)
```
allocates around 10mb for a 200kb file. Stopping `emit` from storing the strings in tokens cuts it down by around 40% and the time by 30%. There surely should be a near enough zero allocation method if we just want to classify and locate the tokens, i.e. 3 integers per token? 


Accessing values through a buffer is not too slow, the rough comparison below has it as about 6-7 times slower but I recon this can be dropped quite a bit using a dict to store token kinds that have a fixed representation (i.e. `Tokens.TRUE` is `true`).
```
tks = collect(tokenize(str))
function access_tok(tks)
    strs = Array{String}(length(tks))
    for i in randperm(length(tks))
        t = tks[i]
        strs[i] = t.val
    end
    strs
end

function access_tok1(tks,iob)
    strs = Array{String}(length(tks))
    for i in randperm(length(tks))
        t = tks[i]
            seek(iob, t.startbyte)
            strs[i] = String(read(iob, t.endbyte-t.startbyte))
    end
    strs
end
```

**Comment by KristofferC** [comment]
Did you remove the string field from the tokens?

**Comment by KristofferC** [comment]
Otherwise they are not bits type and not stack allocated.

**Comment by ZacLN** [comment]
Hmm I did not, let me have a quick look...

That drops allocations from 10 to 2.1 and timings by a third.

The rest of the allocations are probably from reading literals, comments and whitespace. I think these could be removed if 
```
accept_batch(l, is_identifier_char)
str = extract_tokenstring(l)
kind = get(Tokens.KEYWORDS, str, Tokens.IDENTIFIER)
```
in `lex_identifier` was replaced by a somewhat tedious if/else branching function to check whether we are reading a `KEYWORD`
