### ISSUE TITLE
Parse error for 0.1..0.3

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/Tokenize.jl#5]
<img width="203" alt="screen shot 2016-09-23 at 7 22 20 am" src="https://cloud.githubusercontent.com/assets/191822/18784208/9858c75c-815e-11e6-8f12-e7c475256447.png">

I presume the different highlighting shows that there is an error parsing the second `.` in `0.1.` as part of the number.

**Comment by dpsanders** [comment]
``` julia
julia> parse("0.1..0.3")
:(0.1 .. 0.3)
```

**Comment by KristofferC** [comment]
Didn't even know this syntax. Will fix in a few days (away from computer).

**Comment by dpsanders** [comment]
The syntax `..` is defined in the parser but is not given a meaning in Base Julia.
In `ValidatedNumerics.jl` and `IntervalSets.jl`, `a..b`  is used to construct the interval `[a, b]`.

**Comment by KristofferC** [comment]
Ah I see. Is 0... valid? (parsed as 0.0 ..)

**Comment by dpsanders** [comment]
That is parsed as a splat:

``` julia
julia> parse("0...")
:(0...)

julia> dump(ans)
Expr
  head: Symbol ...
  args: Array{Any}((1,))
    1: Int64 0
  typ: Any
```

**Comment by KristofferC** [comment]
> Will fix in a few days (away from computer).

Famous last words..
