### ISSUE TITLE
Investigate into accumulating chars while reading them. 

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Tokenize.jl#51]
Instead of going back in the buffer when we emit a token to read the string accumulate the chara when they are read. Need to keep track of the cols rows though. Might improve performance since we don't need to go back in the buffer to emit a token.

**Comment by ZacLN** [comment]
Sounds good. I'm guessing this will only need to be added to  `lex_comment`, `lex_whitespace`, `lex_quote`, `lex_digit` and `lex_identifier`. For the latter some slight trickery would be needed by passing what's already been read to `readrest`

**Comment by KristofferC** [comment]
I was thinking it could be added to the "lower level" functions `readchar`, `backup!` etc so that the current col and row is always correct.

**Comment by ZacLN** [comment]
Ah yes, that may be better

**Comment by KristofferC** [comment]
#109
