### ISSUE TITLE
Add dot operators

### ISSUE THREAD

**Issue by ZacLN** [JuliaLang/Tokenize.jl#54]
Is this wanted? Semantically I kind of feel either interpretation (i.e. `".+"` as `(".+")` or `(".", "+")` fits. On the parser side of things I think it's just as easy to handle these post-lexing but if there's a need for it I'll have a go at handling it here.

**Comment by KristofferC** [comment]
To me it might as well be handled in the parser.

**Comment by ZacLN** [comment]
Righto!
