### ISSUE TITLE
interpolating strings are incorrectly lexed

### ISSUE THREAD

**Issue by ZacLN** [JuliaLang/Tokenize.jl#63]
```
using Tokenize
str = """
"\$(f(" "))"
"""
collect(tokenize(str))
```
gives us 
```
 1,1-1,6          STRING         "\"$(f(\""
 1,7-1,7          WHITESPACE     " "
 1,8-1,11         STRING         "\"))\""
 1,12-2,0         WHITESPACE     "\n"
 2,1-2,0          ENDMARKER      ""
```

I'm not quite sure if this can be handled properly without the contribution of a parser. One could feasibly count parenthesis until the relevant closing one is found?

**Comment by KristofferC** [comment]
I'm a bit confused about the behavior here. We know that we are reading a `"""` delimited string so why aren't the lexer reading until the terminating `"""` according to https://github.com/KristofferC/Tokenize.jl/blob/cef3395d7f1992f341dc703995507c0c351fe398/src/lexer.jl#L671

**Comment by ZacLN** [comment]
It's only single quote inside the string (\").. that is the triple quotes enclose what is being parsed

**Comment by KristofferC** [comment]
Oh yeah... duh! :P. Yeah that is a tricky one.

**Comment by ZacLN** [comment]
I hate strings

**Comment by KristofferC** [comment]
Can this be closed now?

**Comment by ZacLN** [comment]
Yep
