### ISSUE TITLE
Lexer enters infinite loop when parsing string interpolation having unbalanced brackets

### ISSUE THREAD

**Issue by m-j-w** [JuliaLang/Tokenize.jl#73]
When using OhMyREPL, type `"$(` and an infinite loop is entered. When terminating the REPL (using kill), the traceback shows e.g.
```jl
signal (15): Terminated
while loading no file, in expression starting on line 0
unknown function (ip: 0x7f269660a7bf)
lex_quote at /home/mjw/.julia/v0.6/Tokenize/src/lexer.jl:658           <---- HERE
next_token at /home/mjw/.julia/v0.6/Tokenize/src/lexer.jl:310
next at /home/mjw/.julia/v0.6/Tokenize/src/lexer.jl:75 [inlined]
_collect at ./array.jl:393
rewrite_with_ANSI at /home/mjw/.julia/v0.6/OhMyREPL/src/repl.jl:48
edit_insert at ./LineEdit.jl:467
unknown function (ip: 0x7f2696628ea8)
...
```
The exact lines vary, but are mostly within functions `lex_quote` and `read_string`.

The error occurs in both Julia 0.5 and 0.6, with most recent versions of `Tokenize`.

To me it seems the problem is the while loop at https://github.com/KristofferC/Tokenize.jl/blob/master/src/lexer.jl#L696 where the case of unbalanced brackets is not accounted for.
Unfortunately I don't have a fix although I tried...

**Comment by KristofferC** [comment]
Looks like a problem with https://github.com/KristofferC/Tokenize.jl/pull/64.

CC @ZacLN

**Comment by m-j-w** [comment]
A partial fix, which avoids the infinite loop, but still breaks proper results, is modifying https://github.com/KristofferC/Tokenize.jl/blob/master/src/lexer.jl#L696
```jl
 while o > 0 && c != EOF_CHAR
 #           ^^^^^^^^^^^^^^^^^
```

**Comment by KristofferC** [comment]
Yes that is the exact fix I am trying now

**Comment by KristofferC** [comment]
What do you mean it breaks proper results?

**Comment by m-j-w** [comment]
The 'tokenized' prompt doesn't look correct. The interpolated string is not rendered by OhMyREPL. Probably that is then not an issue in Tokenize.

**Comment by ZacLN** [comment]
I think a fix that gives the wrong results is the best that can be hoped for here so the above fix should be correct? I'm assuming it just treats the rest of the file as being the quoted/interpolated region

**Comment by KristofferC** [comment]
It should be rendered... An error token should be emitted which should be rendered by OhMyREPL

**Comment by KristofferC** [comment]
```
julia> collect(tokenize("\"\$(fdsf\""))
2-element Array{Tokenize.Tokens.Token,1}:
 1,9-1,8          ERROR          ""
 1,9-1,8          ENDMARKER      ""
```

This `ERROR` token has the wrong span.

**Comment by ZacLN** [comment]
Is this likely a result of the recursive calls to lex_quote/read_string?

**Comment by KristofferC** [comment]
Yes. We emit a token that does not get used, which advances the character count so when the correct one is emitted, it does not contain anything.

**Comment by KristofferC** [comment]
I think I fixed it

**Comment by ZacLN** [comment]
``` return doemit ? emit_error(l, Tokens.EOF_STRING) : EMPTY_TOKEN``` on line 661 ?

**Comment by ZacLN** [comment]
and again on 652

**Comment by KristofferC** [comment]
#74
