### ISSUE TITLE
conflicting unicode characters

### ISSUE THREAD

**Issue by ZacLN** [JuliaLang/Tokenize.jl#88]
When there are multiple codes for indistinguishable unicode characters Julia only uses one 'true' version for `Symbol`s .i.e.
```
str = "µ"
(string(parse(str)) == str) == false
```
for U+00b5
and
```
str = "μ"
(string(parse(str)) == str) == true
```
for U+03bc
can we recreate this behaviour?

**Comment by Keno** [comment]
This is now fixed in CSTParser
